version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
       - "3000:3000"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: -config.file=/etc/prometheus/prometheus.yml
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    volumes:
      - ./loki/loki-config.yml:/mnt/config/loki-config.yml
    ports:
      - "3100:3100"
    command: -config.file=/mnt/config/loki-config.yml

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yml:/mnt/config/promtail-config.yml
      - /var/log:/var/log # host logs
    depends_on:
      - loki
    command: -config.file=/mnt/config/promtail-config.yml
