global:
    scrape_inverval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
        - targets: 
          - localhost:9090
  - job_name: redis_exporter
    static_configs:
        - targets: 
          - redis-exporter:9121
  
