apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://172.18.0.2:3100
    jsonData:
      timeout: 60
      maxLines: 1000

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    jsonData:
      tiemout: 60
      maxLines: 1000
